# Exploring the Jumia Smart TV Catalogue Dataset 

## by (Olatunji Jola)

## Introduction
> The Jumia smart TV dataset contains 1615 smart TV listing Scraped from the Jumia website. The data set contains 1615 Observations and 7 variables. The data was scraped using scrapy as a json file name `'jumia_tv_catalogue.json'` and given descrpitive column names. In this notebook, I will be cleaning up the dataset and then analysing the dataset for patterns in the aim of performing a market research on the best smart tv in different categories, by size, features, ratings, and pricing and to check for the seller on the jumia website with the best offerings in terms of quality, ratings and pricing.

In [64]:
# import all packages and set plots to be embedded inline 
import pandas as pd
from pandas import json_normalize
import numpy as np
import json
import matplotlib .pyplot as plt
import seaborn as sb
import re

%matplotlib inline

In [65]:
# import the json
with open ('jumia_tv_catalogues.json', 'r') as file:
    smart_tv_catalogue = json.load(file)

In [66]:
# loading the json file into a dataframe
pd_tv_catalogue = json_normalize(smart_tv_catalogue)

### Preliminary Wrangling 

in this Section various observation are made about the dataset for cleaning purposes

In [67]:
pd_tv_catalogue.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1652 entries, 0 to 1651
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           1652 non-null   object
 1   brand          1646 non-null   object
 2   price          1646 non-null   object
 3   ratings        1652 non-null   object
 4   specification  1652 non-null   object
 5   Seller_name    1652 non-null   object
 6   seller_rating  1426 non-null   object
 7   url            1652 non-null   object
dtypes: object(8)
memory usage: 103.4+ KB

In [68]:
pd_tv_catalogue.sample(20)

,name,brand,price,ratings,specification,Seller_name,seller_rating,url
1402,Samsung 65 Inch Crystal Ultra HD 4K Smart TV (...,Samsung,"₦ 680,000",0 out of 5,"[65 inch 4K UHD 3840 x 2160 LED Panel, HDR10, ...",Luchi's Store,94%,https://www.jumia.com.ng/samsung-65-inch-cryst...
580,Polystar 40 Inches Android Smart Curved TV,Polystar,"₦ 144,000",0 out of 5,"[Display Size; 40 Inches, Resolution: HD (High...",Office Comfort Enterprises,60%,https://www.jumia.com.ng/polystar-40-inches-an...
36,"Vision 43'' UHD Smart 4K TV+Netflix,Youtube,Ma...",Vision,"₦ 128,490",4 out of 5,"[Latest Model, Quad Core Processor, Cinema Exp...",cydone gas,74%,https://www.jumia.com.ng/vision-43-uhd-smart-4...
223,TCL 55 Inch Ultra Slim Smart UHD Android 4K TV,TCL,"₦ 400,000",0 out of 5,"[55 inch LED UHD Android TV, OS Android P UI S...",Bryan's store,100%,https://www.jumia.com.ng/tcl-55-inch-ultra-sli...
938,Polystar 40 INCH SMART CURVED LED TV + Free Wa...,Polystar,"₦ 144,000",0 out of 5,"[Features: Wi-Fi, Colour: Black, Product warr...",Office Comfort Enterprises,60%,https://www.jumia.com.ng/polystar-40-inch-smar...
1059,Samsung 50 Inch AU8000 UHD Crystal Smart LED C...,Samsung,"₦ 450,000",0 out of 5,"[50 inch 4K UHD 3840 x 2160 LED Panel, HDR10, ...",sammesmart concept,None,https://www.jumia.com.ng/samsung-50-inch-au800...
727,"Samsung 55"" AU8000 Crystal UHD 4K HDR Smart ...",Samsung,"₦ 520,000",0 out of 5,[Complies with the CTA's 4K Ultra High-Definit...,Worldmartin,100%,https://www.jumia.com.ng/samsung-55-au8000-cry...
764,"Syinix 43"" Smart FULL HD Android TV+Netflix,Yo...",Syinix,"₦ 164,000",5 out of 5,"[Android Google TV​, Up to 5000 apps with Goog...",Kendo,80%,https://www.jumia.com.ng/syinix-43-smart-full-...
1092,Samsung 43 Inch Premium HDR+ Class Crystal UHD...,Samsung,"₦ 370,000",0 out of 5,"[43 inch 4K UHD 3840 x 2160 LED Panel, HDR10, ...",Worldmartin,100%,https://www.jumia.com.ng/samsung-43-inch-premi...
563,Samsung 75 Inch Class HDR 4K UHD Smart QLED TV...,Samsung,"₦ 2,200,000",0 out of 5,"[4K UHD 3840 x 2160 Quantum Dot LED Panel, HDR...",Worldmartin,100%,https://www.jumia.com.ng/samsung-75-inch-class...
710,"Hisense 43"" A4G SMART FHD TV - 43A4G",Hisense,"₦ 205,618",0 out of 5,"[Model: TV 43 A4G, 43 Inches TV, Smart TV, LED...",Numartng,50%,https://www.jumia.com.ng/hisense-43-a4g-smart-...
211,Hisense 55”Android UHD 4K Smart TV+ JBLSpeaker...,Hisense,"₦ 345,800",4 out of 5,"[55”Android TV, Dolby vision HDR, Dolby Atmos,...",Jamiu Lagos,100%,https://www.jumia.com.ng/hisense-55android-uhd...
1112,Samsung Premium 75 Inch UHD Class Certified Sm...,Samsung,"₦ 1,300,000",0 out of 5,"[75 inch 4K UHD 3840 x 2160 LED Panel, HDR10, ...",Bryan's store,100%,https://www.jumia.com.ng/samsung-premium-75-in...
92,Samsung 43 Inches T5300 HD Smart TV 2020 with ...,Samsung,"₦ 267,030",0 out of 5,"[Series -5, Resolution - 1,920 x 1,080, HDMI -...",Jumia,100%,https://www.jumia.com.ng/samsung-43-inches-t53...
178,LG Gencool - Inverter Split Unit Airconditione...,LG,"₦ 265,000",3.8 out of 5,"[Gencool - B, 1.5 KVA Generator, Energy Effici...",Kendo,80%,https://www.jumia.com.ng/gencool-inverter-spli...
1088,"Hisense 70''Smart UHD 4K TV+Netflix,Youtube,Pr...",Hisense,"₦ 520,900",0 out of 5,[],Luchi's Store,94%,https://www.jumia.com.ng/hisense-70smart-uhd-4...
428,Samsung 75 Inch Premium Class UHD Q60A HDR+ Sm...,Samsung,"₦ 2,000,000",0 out of 5,"[75 inch 4K UHD 3840 x 2160 QLED Panel, Quantu...",Smart Center,50%,https://www.jumia.com.ng/samsung-75-inch-premi...
670,"Hisense 65"" 4K UHD Smart LED TV",Hisense,"₦ 360,000",0 out of 5,[],MEGATRON NG,66%,https://www.jumia.com.ng/hisense-65-4k-uhd-sma...
1469,"Amani 65"" INCHES SMART FULL HD LED TV WITH 1 Y...",Amani,"₦ 290,000",0 out of 5,"[65"" SMART FULL HD LED, Browser: Yes, Wifi: Ye...",ELO GLOBAL,60%,https://www.jumia.com.ng/amani-65-inches-smart...
713,Samsung 55inch Ultra Slim Certified UHD Smart ...,Samsung,"₦ 520,000",0 out of 5,"[55 inch 4K UHD 3840 x 2160 LED Panel, HDR10, ...",Bryan's store,100%,https://www.jumia.com.ng/samsung-55inch-ultra-...

#### How many unique brands are in the dataset

In [69]:
# Checking for unique brands

pd_tv_catalogue['brand'].unique()

array(['WEYON', 'Amani', 'TCL', 'Hisense', 'Rock', 'Polystar', 'Infinity',
       'Energy', 'Vision', 'Transparent', 'BUC', 'LG', 'UFC', 'Syinix',
       'Samsonic', 'Amaz', 'Samsung', 'MK', 'Sony', 'Konka', 'Maxi',
       'Felicity Solar', 'itel', 'Sanyo', 'Infinix', 'Electronic Arts',
       'Sonix', 'High', 'XIAOMI', 'Bruhm', 'Luminous', 'Royal',
       'Panasonic', 'Rilsopower', 'Skyworth', 'Homeflower', 'XTRAPOWER',
       'Aida', None, 'Mercedes Amg', 'Google', 'Famicare', 'Dexter'],
      dtype=object)

##### Observation
45 unique brands can be observed overall. However, the Felicity Solar brand name is not a TV brand.

#### Check for Duplicates

In [70]:
# columns to check for duplicated values
column_names =  ['name', 'brand', 'price', 'ratings', 'Seller_name', 'seller_rating']

# checking for duplicates
duplicates = pd_tv_catalogue.duplicated(subset = column_names, keep = False)

pd_tv_catalogue[duplicates].sort_values(by = 'name')

,name,brand,price,ratings,specification,Seller_name,seller_rating,url
1454,Amaz Real 32''inch Dual Glass TV +18 Months Wa...,Amaz,"₦ 70,080",0 out of 5,[],AMAZ official shop,60%,https://www.jumia.com.ng/amaz-real-32inch-dual...
750,Amaz Real 32''inch Dual Glass TV +18 Months Wa...,Amaz,"₦ 70,080",0 out of 5,[],AMAZ official shop,60%,https://www.jumia.com.ng/amaz-real-32inch-dual...
1230,"Hisense 50'' Smart UHD 4K TV+ Bluetooth, Netfl...",Hisense,"₦ 222,999",0 out of 5,"[50'' 4K UHD TV, BLUETOOTH, NETFLIX, YOUTUBE, ...",Homewarehouse,60%,https://www.jumia.com.ng/hisense-50-smart-uhd-...
723,"Hisense 50'' Smart UHD 4K TV+ Bluetooth, Netfl...",Hisense,"₦ 222,999",0 out of 5,"[50'' 4K UHD TV, BLUETOOTH, NETFLIX, YOUTUBE, ...",Homewarehouse,60%,https://www.jumia.com.ng/hisense-50-smart-uhd-...
881,"Hisense 50''QLED Smart 4K TV+Netflix,Youtube A...",Hisense,"₦ 320,000",0 out of 5,[],Real EmmyGod Store,50%,https://www.jumia.com.ng/hisense-50qled-smart-...
...,...,...,...,...,...,...,...,...
412,Syinix 50'' INCHES SMART ANDROID UHD 4K TV + F...,Syinix,"₦ 265,000",0 out of 5,"[50'' Smart 4K UHD TV, Resolution: (3839 x 216...",Luchi's Store,94%,https://www.jumia.com.ng/syinix-50-inches-smar...
1368,TCL 43 Inches Full HD Smart Certified Android ...,TCL,"₦ 230,000",0 out of 5,"[Supported Apps: Netflix, You Tube, Hotstar, Z...",Worldmartin,100%,https://www.jumia.com.ng/tcl-43-inches-full-hd...
1382,TCL 43 Inches Full HD Smart Certified Android ...,TCL,"₦ 230,000",0 out of 5,"[Supported Apps: Netflix, You Tube, Hotstar, Z...",Worldmartin,100%,https://www.jumia.com.ng/tcl-43-inches-full-hd...
945,TCL 55 Inch Ultra Slim Smart UHD Android 4K TV,TCL,"₦ 400,000",0 out of 5,"[55 inch LED UHD Android TV, OS Android P UI S...",Bryan's store,100%,https://www.jumia.com.ng/tcl-55-inch-ultra-sli...
223,TCL 55 Inch Ultra Slim Smart UHD Android 4K TV,TCL,"₦ 400,000",0 out of 5,"[55 inch LED UHD Android TV, OS Android P UI S...",Bryan's store,100%,https://www.jumia.com.ng/tcl-55-inch-ultra-sli...

In [71]:
#number of duplicated items
pd_tv_catalogue.duplicated(subset = column_names, keep = 'first').sum()

40

##### Observation

There are 30 duplicated items in the dataset

### Cleaning

In this section the observed issues with the dataset will be addressed.

The following cleaning operations will be carried out.

- drop duplicated rows
- Remove entries that are not TVs
- Make the `name` column more brief
- change the `Seller` column to be all small letters
- make the price column a number and describe the currency in the price column title
- for prices defined by price ranges find the average price.
- make the seller_rating column categorical variable
- rating should be categorical variable
- address missing values
- expand the specification column focusing on key metrics eg. ports, screen_resolution, screen_types, and screen_size

#### Make a copy

In [72]:
pd_tv_catalogue_default = pd_tv_catalogue.copy()

#### Drop duplicates

In [73]:
#drop duplicate rows
pd_tv_catalogue.drop_duplicates(subset = column_names, inplace= True)

#### Test

In [74]:
pd_tv_catalogue.duplicated(subset = column_names).sum()

0

#### Drop Entries that are not TVs

most entries that are TVs contain any of the following words in their names.

- TV, Tv, inches, #", UHD, 4K, Full HD, Television  or smart

In [75]:
# Drop rows that do not meet the condition in the pattern 
pattern = 'TV|inch|\"|uhd|4k|full hd|television|smart'
contains_no_TV = pd_tv_catalogue.name.str.contains(pattern, flags=re.IGNORECASE, regex =True)
pd_tv_catalogue.drop(pd_tv_catalogue[~contains_no_TV].index, inplace = True)
pd_tv_catalogue.reset_index(drop = True, inplace = True)

#### Test

#### Make the name column more brief

To make the name column more brief, the folowing steps will be taken.

1. Split the name column using the keyword 'TV' as the delimiter.
2. Merge with expanded output with the subset of the `pd_tv_catalogue` using the index, and effectively remplacing the previous name column.
3. append 'TV' to the names in the new name column.

In [76]:
# split the name column
pd_tv_catalogue_name_split = pd_tv_catalogue.name.str.split(r'(?i)TV', regex = True, expand = True)[0]

# merge the two dfs to create a new dataframe with the new name column
pd_tv_catalogue_coumn_list = ['brand','price', 'ratings', 
                              'specification', 'Seller_name', 'seller_rating', 'url']
pd_tv_renamed = pd.merge(pd_tv_catalogue_name_split,pd_tv_catalogue[pd_tv_catalogue_coumn_list], 
         left_index = True, right_index = True)

# change the name and seller_name column header
pd_tv_renamed.columns = ['name','brand','price', 'ratings', 
                        'specification', 'seller_name', 'seller_rating', 'url']
#append the names with the word tv; convert all to lowercase.
pd_tv_renamed.name = pd_tv_renamed.name.apply(lambda x: '{}tv'.format(x.lower()))

#### Test

In [77]:
test_name_df = pd.merge(pd_tv_catalogue.name, pd_tv_renamed.name, left_index = True, right_index = True)
test_name_df.head(10)

,name_x,name_y
0,"WEYON 32"" Inches HD Smart TV (32WASN) +1 Year...","weyon 32"" inches hd smart tv"
1,Amani 43”Inch 4k UHD Smart Android Wi-fi Tv A...,amani 43”inch 4k uhd smart android wi-fi tv
2,TCL 43-Inch Android Smart FHD TV,tcl 43-inch android smart fhd tv
3,"Hisense 55''Smart UHD 4K TV+Bluetooth,Netflix,...",hisense 55''smart uhd 4k tv
4,"Hisense 55''Smart UHD 4K Framless TV+Netflix,...",hisense 55''smart uhd 4k framless tv
5,"Rock 43"" 4k SMART ANDROID UHD LED TV + FREE WA...","rock 43"" 4k smart android uhd led tv"
6,Polystar 40 INCH SMART CURVED LED TV + Free Wa...,polystar 40 inch smart curved led tv
7,Hisense 43''Smart TV + Netflix&Youtube APP 12 ...,hisense 43''smart tv
8,"WEYON 39"" Inches LED Smart TV (39WASN) +1 Year...","weyon 39"" inches led smart tv"
9,Hisense 40 Inches Smart Frameless TV + 12 Mont...,hisense 40 inches smart frameless tv

#### Make the price column numeric
To achieve this; 

1. All special characters i.e '₦',',' and space will first be removed, 
2. drop nulls, 
3. deal with price ranges by finding there averages.
4. then convert to integer.

In [78]:
# Remove all special character from price
pd_tv_renamed.price = pd_tv_renamed.price.str.replace(',', '').str.replace('₦','').str.strip()

In [79]:
pd_tv_renamed.price

0                  79990
1                 128490
2                 169900
3                 265000
4                 222000
              ...
1563              109900
1564              167900
1565              185300
1566              161460
1567    117499 -  117999
Name: price, Length: 1568, dtype: object

In [80]:
# remove nulls in the price column

filter = pd_tv_renamed.price.isnull()
pd_tv_renamed.drop(pd_tv_renamed[filter].index, axis = 0, inplace = True)
pd_tv_renamed.reset_index(drop =True, inplace  = True)

In [81]:
# find the average of price ranges.
price_ranges = pd_tv_renamed.price.str.split(' - ', expand = True)
price_ranges[0] = price_ranges[0].astype('int')
price_ranges[1] = price_ranges[1].astype('float')

In [82]:
price_ranges['average'] = price_ranges.agg('mean', axis = 1)

In [83]:
column = ['name', 'brand', 'price', 'ratings',
          'specification', 'seller_name', 
          'seller_rating', 'url']
pd_tv_price_cleaned = price_ranges.merge(pd_tv_renamed[column], left_index = True, right_index = True)

In [84]:
pd_tv_price_cleaned.drop([0,1, 'price'], axis = 1, inplace = True)
pd_tv_price_cleaned.columns =['price','name', 'brand', 'ratings',
                              'specification', 'seller_name', 
                              'seller_rating', 'url']

In [85]:
pd_tv_price_cleaned['price'] = pd_tv_price_cleaned.price.astype('int')

#### Test

In [86]:
pd_tv_price_cleaned.price.dtype

dtype('int32')

#### Make the ratings column numerical variable

- Extract the rating as number from the ratings clumn
- convert to float
- drop the ratings column

In [87]:
# Extract the ratings from the the 
# ratings columns name into a new column rating
pd_tv_price_cleaned['rating'] = pd_tv_price_cleaned.ratings.str.extract(r"(\d?\.?\d)")

In [88]:
# convert he rating column to float type.
pd_tv_price_cleaned['rating'] = pd_tv_price_cleaned.rating.astype('float')

In [89]:
pd_tv_price_cleaned.drop('ratings', axis = 1, inplace = True)

#### Test

In [90]:
pd_tv_price_cleaned[pd_tv_price_cleaned.rating.isnull()]

Empty DataFrame
Columns: [price, name, brand, specification, seller_name, seller_rating, url, rating]
Index: []

#### Convert seller ratings to numerical variables
- extract the numerical content of the seller_rating column
- 205 observaions has no seller_rating this is due tobeing new sellers
- those null values will be replaced with 0
- The column will be converted to integers

#### Code

In [91]:
#extract numerical content of seller_rating column
pd_tv_price_cleaned.seller_rating = pd_tv_price_cleaned.seller_rating.str.extract(r"(\d+)")

# Repalce Nans with 0
pd_tv_price_cleaned.seller_rating.fillna(0, inplace = True)

# convert type to integer
pd_tv_price_cleaned.seller_rating = pd_tv_price_cleaned.seller_rating.astype(int)

#### Test

In [94]:

assert pd_tv_price_cleaned.seller_rating.dtype == 'int'

In [95]:
pd_tv_price_cleaned

,price,name,brand,specification,seller_name,seller_rating,url,rating
0,79990,"weyon 32"" inches hd smart tv",WEYON,"[Model：32WASN, Panel size: 32, Excellent Pictu...",WEYON Official Store-Sea-COD,60,https://www.jumia.com.ng/weyon-32-inches-hd-sm...,4.7
1,128490,amani 43”inch 4k uhd smart android wi-fi tv,Amani,[],cydone gas,74,https://www.jumia.com.ng/amani-43inch-4k-uhd-s...,5.0
2,169900,tcl 43-inch android smart fhd tv,TCL,"[12 Months Warranty, Certified Android Smart T...",Clem Fortune,100,https://www.jumia.com.ng/tcl-43-inch-android-s...,4.3
3,265000,hisense 55''smart uhd 4k tv,Hisense,"[55'' 4K UHD TV, BLUETOOTH, NETFLIX, YOUTUBE, ...",F & G Electronics,86,https://www.jumia.com.ng/hisense-55smart-uhd-4...,4.9
4,222000,hisense 55''smart uhd 4k framless tv,Hisense,[],Kendo,80,https://www.jumia.com.ng/hisense-55smart-uhd-4...,0.0
...,...,...,...,...,...,...,...,...
1557,109900,hisense 32” led smart hd tv,Hisense,"[Series A4G, Diagonal Class - 32 Inches, Color...",Franco global electronics Ltd.,100,https://www.jumia.com.ng/32high-definition-led...,4.9
1558,167900,hisense 43” smart frameless tv,Hisense,"[Screen Size: 43″ Smart tv, Screen Type: LED B...",Franco global electronics Ltd.,100,https://www.jumia.com.ng/hisense-43-smart-fram...,4.8
1559,185300,"ufc ''55"" inch 4k ultra-hd smart led android tv",UFC,"[Transparent Smart TV ., RAM 4G 4K HDR, 55 INC...",EbocasBabyClothings,80,https://www.jumia.com.ng/ufc-55-inch-4k-ultra-...,4.4
1560,161460,"hisense 43"" inches led smart tv",Hisense,[​],Jumia,100,https://www.jumia.com.ng/hisense-43-inches-led...,5.0
1561,117749,"infinity 43"" inches smart tv",Infinity,"[43"" SMART FULL HD LED, FREE WALL HANGER, Fram...",B AND Q COLLECTIBLES,74,https://www.jumia.com.ng/infinity-43-inches-sm...,4.1

#### Specification

In treating the specification column I will be extracting from he specification column, information futher divided into four caegories.

- Screen size e.g, 32, 40, 43 
- Screen Resolution e.g., Full HD,4k, 8k
- Screen types e.g. LED, LCD,OLED,QLED
- Ports